### ISSUE TITLE
Crash on world start up

### ISSUE THREAD

**Issue by Reginald-Halifrax** [Zarklord/GemCore#10]
this is a crash from the update today.
and yes i tried doing it completely on its own.

[00:03:52]: error loading module 'bit' from file '../mods/workshop-1378549454\scripts\bit.lua':
	[string "cannot OLDFILEACCESSMETHOD @../mods/workshop-1378549454\scripts..."]:98: '(' expected near '.'
LUA ERROR stack traceback:
        =[C] ?
        =[C] in function 'require'
        ../mods/workshop-1378549454/modmain.lua(39,1) in main chunk
        =[C] in function 'xpcall'
        scripts/util.lua(709,1) in function 'RunInEnvironment'
        scripts/mods.lua(511,1) in function 'InitializeModMain'
        scripts/mods.lua(485,1) in function 'LoadMods'
        scripts/main.lua(267,1) in function 'ModSafeStartup'
        scripts/main.lua(327,1)
        =[C] in function 'SetPersistentString'
        scripts/mainfunctions.lua(26,1) in function 'SavePersistentString'
        scripts/modindex.lua(77,1)
        =[C] in function 'GetPersistentString'
        scripts/modindex.lua(64,1) in function 'BeginStartupSequence'
        scripts/main.lua(326,1) in function 'callback'
        scripts/modindex.lua(542,1)
        =[C] in function 'GetPersistentString'
        scripts/modindex.lua(516,1) in function 'Load'
        scripts/main.lua(325,1) in main chunk
[00:03:52]: [string "scripts/mainfunctions.lua"]:1029: variable 'global_error_widget' is not declared
LUA ERROR stack traceback:
        =[C] in function 'error'
        scripts/strict.lua(23,1)
        scripts/mainfunctions.lua(1029,1)
        =[C] in function 'SetPersistentString'
        scripts/mainfunctions.lua(26,1) in function 'SavePersistentString'
        scripts/modindex.lua(77,1)
        =[C] in function 'GetPersistentString'
        scripts/modindex.lua(64,1) in function 'BeginStartupSequence'
        scripts/main.lua(326,1) in function 'callback'
        scripts/modindex.lua(542,1)
        =[C] in function 'GetPersistentString'
        scripts/modindex.lua(516,1) in function 'Load'
        scripts/main.lua(325,1) in main chunk
[00:03:52]: DoLuaFile Error: (null)

**Comment by Zarklord** [comment]
A fix will be out within a hour.

**Comment by Zarklord** [comment]
fixed #11 .
